# Generated by Django 5.0.4 on 2024-05-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bg_image',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
